### PR TITLE
Upgrade Spring AI to 1.0.0-M4

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Update Spring AI BOM to 1.0.0-M4
 - Add Amazon Bedrock Converse Boot starter

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hey @ilayaperumalg, thanks for that! Is the 1.0.0-M4 ready for Spring Boot `3.4.0` which will be released today?

**Comment by ilayaperumalg** [comment]
@mhalbritter Spring AI M4 uses Spring Boot `3.3.4` for the auto-configuration, boot starters and testing. As a side note, starting M4, we also have removed Spring Boot dependency for the core modules. Hence, it will be for the boot starters only.  Testing against `3.4.0` milestone versions (3.4.0-RC1) is TBD.

**Comment by ilayaperumalg** [comment]
@mhalbritter This specific starter was removed. will update the PR.

**Comment by mhalbritter** [comment]
Thanks @ilayaperumalg !

**Comment by ilayaperumalg** [comment]
@mhalbritter Thank you for the review and merge!

**Pull request closed without merging**
