### PR TITLE
Upgrade to Spring Boot Admin 2.2.1

### PR DESCRIPTION
**Pull request by joshiste**

### CODE REVIEW

**Comment by snicoll** [comment]
@joshiste I don't see `2.2.1` on Maven Central, have I missed something?

**Comment by joshiste** [comment]
Oh, that was quick. I just hit release on oss.sonatype.org a few moments ago...
The sync usually takes some time....

**Comment by snicoll** [comment]
I see. Can you please create the issue only once you've validated everything is available on Maven central? If you can ping here when it's done, I'd appreciate it.

**Comment by joshiste** [comment]
@snicoll ping ;)
http://repo2.maven.org/maven2/de/codecentric/spring-boot-admin-server/2.2.1/spring-boot-admin-server-2.2.1.pom

**Comment by snicoll** [comment]
Ah, I can see the traffic on Maven Central is lighter than usual :)

Will upgrade shortly, Thanks.

**Comment by snicoll** [comment]
FYI, while this was merged, this won't show up on production shortly as usual as we currently have a problem with our CI system.

**Pull request closed without merging**
