### PR TITLE
Upgrade to Okta starter 1.2.0

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the update @bdemers. Do you have compatibility build against Spring Boot 2.2? We'd like to make sure this is covered.

**Comment by bdemers** [comment]
I’ll get on that this week!

**Comment by bdemers** [comment]
@snicoll I found a couple issues, one in spring-sec and this one: spring-projects/spring-boot#17035

**Comment by snicoll** [comment]
@bdemers thanks for the feedback and trying but what does that mean concretely? Is it broken or is the spring security a corner case issue?

**Comment by bdemers** [comment]
Sorry @snicoll, I wasn’t clear about the spring sec issuer, that one is a potential vuln, so it is private (and unrelated to the linked one above)

**Comment by snicoll** [comment]
What link? Can you please confirm that the current generation works with SB 2.2? If not, we need to disable it here.

**Comment by bdemers** [comment]
@snicoll fixed in #144

**Comment by snicoll** [comment]
Thanks @bdemers

**Pull request closed without merging**
