### PR TITLE
Upgrade spring-cloud-gcp version to 3.4.3 and 4.0.0

### PR DESCRIPTION
**Pull request by alicejli**
Upgrade spring-cloud-gcp version to 3.4.3 and add new compatibility range for v4.0.0

### CODE REVIEW

**Review by meltsufin — APPROVED** [review]

**Comment by emmileaf** [comment]
@alicejli Sorry I couldn't figure out how to comment/suggest on unedited lines, but we should bump this upper bound to 3.1.0-M1 as well. Thanks! https://github.com/spring-io/start.spring.io/blob/b20d0545c1780044455be6b196cdf6e347a17402/start-site/src/main/resources/application.yml#L1491

**Comment by alicejli** [comment]
> @alicejli Sorry I couldn't figure out how to comment/suggest on unedited lines, but we should bump this upper bound to 3.1.0-M1 as well. Thanks!
> 
> https://github.com/spring-io/start.spring.io/blob/b20d0545c1780044455be6b196cdf6e347a17402/start-site/src/main/resources/application.yml#L1491

@emmileaf done, thanks!

**Comment by emmileaf** [comment]
@alicejli I think your last commit modified an incorrect line, the change I was referring to is in a different section. Could you revert it and update in this section instead? Sorry for the confusion!

https://github.com/spring-io/start.spring.io/blob/b20d0545c1780044455be6b196cdf6e347a17402/start-site/src/main/resources/application.yml#L1489-L1492

@bclozel Could we re-open this PR, or should we submit a new one to fix?

**Comment by emmileaf** [comment]
Thanks for the help @bclozel!

**Comment by bclozel** [comment]
Thanks for the PR, @emmileaf ! The change is now live.

**Pull request closed without merging**
