### PR TITLE
Upgrade to Vaadin 24.1.8, 24.0.14, 23.3.22

### PR DESCRIPTION
**Pull request by ZheSun88**

### CODE REVIEW

**Comment by snicoll** [comment]
@ZheSun88 isn't Vaadin 24.0 EOL?

**Comment by ZheSun88** [comment]
yes, 24.0 is end of Life. 24.0.14 is the last one we released.

**Comment by snicoll** [comment]
I don’t know. What are users supposed to use with those Spring Boot versions ?

**Comment by ZheSun88** [comment]
let me ask in the team. will get back here later.

**Comment by snicoll** [comment]
It doesn't hurt to get to the latest release anyway. When you get a min, we can discuss how to address the EOL versions. Thanks again!

**Comment by ZheSun88** [comment]
Thanks @snicoll , i just talked with the team, and did some test. 

Vaadin 24.1 is still compatible with springboot 3.0, so we want to merge the compatibilityRange for V24.0 and V24.1. 
also, it seems springboot 2.6 is not an option on start.spring.io, so we can remove the entry for vaadin 23.2.

**Comment by snicoll** [comment]
Thanks. We keep Spring Boot 2.6 compat for users upgrading but we will soon remove it indeed. How about 2.7? Is 23.3 still supported? Where can I see the EOL information for Vaadin?

You can submit another PR or I can take care of it, whichever you prefer.

**Comment by ZheSun88** [comment]
Vaadin 23.3 is compatible with spring boot 2.7. 
The EOL information for Vaadin can be found from vaadin.com/roadmap, here is a screenshot
image

**Pull request closed without merging**
