### PR TITLE
Fix MySQL coordinate errors

### PR DESCRIPTION
**Pull request by BingZi-233**

### CODE REVIEW

**Comment by BingZi-233** [comment]
This is a very small change. I don't think it is necessary for me to sign the agreement.

**Comment by wilkinsona** [comment]
Thanks for the PR but the coordinates are correct as they currently are. Please see https://github.com/spring-io/start.spring.io/issues/1013 for details.

**Comment by BingZi-233** [comment]
Just now, I tried to obtain dependencies from the central warehouse. It seems that he is not working normally at present.

**Comment by wilkinsona** [comment]
The artifact is available from Central: https://repo.maven.apache.org/maven2/com/mysql/mysql-connector-j/. Make sure you're using 8.0.31.

**Pull request closed without merging**
