### PR TITLE
Relative links in index.html to assets

### LINKED ISSUE #456: Absolute URL links to JS files
The `index.html` has absolute path links:

image (1)

It is best to replace them with relative links for hosting Initilizr via a proxy in k8s cluster

### PR DESCRIPTION
**Pull request by BoykoAlex**
Fixes #456

### CODE REVIEW

**Comment by oodamien** [comment]
The reload is broken on dev mode.

**Comment by snicoll** [comment]
I've reverted the commit as you requested @oodamien in https://github.com/spring-io/start.spring.io/commit/13f031198491689cfd298e4dc8fc2e23f18dfef4

**Comment by BoykoAlex** [comment]
@snicoll I see, thanks for letting me know... Lets just move the fix to `webpack.prod.js` then. I'll update the PR

**Comment by BoykoAlex** [comment]
A new PR is created with the production build fixed only: #463 
Tried running the UI in dev mode seem to reload on changes now.

**Pull request merged**
