### PR TITLE
Upgrade to Vaadin 8.7.0

### PR DESCRIPTION
**Pull request by mehdi-vaadin**

### CODE REVIEW

**Comment by snicoll** [comment]
@mehdi-vaadin do we want to upgrade to a new feature release in a maintenance release here?

**Comment by mehdi-vaadin** [comment]
@snicoll We would like to upgrade to this new feature release (`8.7.0`). But I'm not sure if I fully understand your question.

**Comment by snicoll** [comment]
`1.5.x` is in maintenance mode, I am asking if switch to a new Vaadin feature release is expected. I am ok either way, just wondering.

**Comment by mehdi-vaadin** [comment]
Yes, it's totally fine.

**Pull request closed without merging**
