### PR TITLE
Add links to HELP.md based on project's build system

### PR DESCRIPTION
**Pull request by jlstrater**
Thanks again for your help @snicoll 

Feel free to squash the commits and add any polish you'd like. In particular, I'm not sure what you're looking for for the tests.

### CODE REVIEW

**Comment by jomartin-999** [comment]
Hi @jlstrater,

Thank you so much for the pull request.  We really appreciate your help on adding additional content to the Help.md file.

As the Help.md file is still fairly new, we’re working on a strategy we’d like to have in place to set a precedent for what types of links we’d like to include.  

After a team discussion we’ve decided that links in the Help.md file should only point to official documentation regarding the technology.  

For your pull request, what we would like to keep are the links to the official Gradle and Maven documentation and remove the links to the build scans. Users can discover more information regarding the build scans from the Gradle site.

**Comment by jlstrater** [comment]
1.) It would have been really nice to know this when I emailed and it was suggested I submit this. As the build scan recommendation was the only reason my time was approved to work on this if you want those changes someone else will need to make them. It also means I'm less likely to be able to contribute in the future.

2.) @jomartin-999 You should really consider updating your profile to show you are associated with the project. I thought you were messing with me.

**Comment by wilkinsona** [comment]
Hi, @jlstrater. We’re still finding our way a bit with the new help.md feature. Sorry that you’ve been caught up in that.

We’ve discussed your proposed changes among the team again and have changed our opinion about what we think we should link to. While we don’t want to blur the lines between Maven and Gradle by linking to scans.gradle.com for Maven projects, we’re happy to link to scans.gradle.com for Gradle projects. We think it fits with starting a project using Gradle as a build scan will allow users to visualise the structure of their new project’s build and its dependencies. If you are happy for your changes to be merged in this form, please re-open this pull request and we’ll be happy to refine and merge it.

As we’ve said, the help.md feature is new and we’re still finding our feet with it. As we add content to the file and users start giving us feedback on its usefulness, we’ll be better-placed to add and remove content to best meet our goals and our users’ needs. Thanks for bearing with us while we get there.

**Comment by jlstrater** [comment]
Ok. I think we can do that. I hope we can revisit the link on Maven projects in six months or so.

**Comment by wilkinsona** [comment]
Thanks very much, @jlstrater.

**Comment by wilkinsona** [comment]
Thanks very much for making your first contribution to start.spring.io, @jlstrater. The proposed changes along with a [little bit of polish](https://github.com/spring-io/start.spring.io/commit/5db16160f8ffa86fad2fb19d44ff46eba25c8f33) have been merged into master and will be live shortly.

**Pull request closed without merging**
