### PR TITLE
Upgrade to Vaadin 24.5.8

### PR DESCRIPTION
**Pull request by ZheSun88**

### CODE REVIEW

**Comment by mhalbritter** [comment]
Thanks @ZheSun88 !

**Comment by ZheSun88** [comment]
Hi @mhalbritter 

it seems from spring.io.. our dependency is not compitible with spring 3.4.0, but only with 3.3. x
image

i wonder if the compatibleRange works here. 

```
mappings:
          - compatibilityRange: "[3.3.0,3.5.0-M1)"
            version: 24.5.8
```

**Comment by mhalbritter** [comment]
Thanks for letting me know. Fixing it :)

**Comment by mhalbritter** [comment]
Fixed now.

**Pull request closed without merging**
