### PR TITLE
Upgrade to Spring Cloud 2021.0.1

### PR DESCRIPTION
**Pull request by ryanjbaxter**

### CODE REVIEW

**Comment by snicoll** [comment]
@ryanjbaxter going forward, could you please validate that a Spring Cloud snapshot is actually available before submitting the PR? It isn't and our metadata tests are failing as a result.

**Comment by ryanjbaxter** [comment]
Sorry @snicoll, we had some issues with some of our Jenkins jobs.  The artifacts should be there no, can you try again?

**Comment by ryanjbaxter** [comment]
Ugh sorry about that.  I fixed the stream build and ran the build of start.spring.io locally and it passed.  Hope its fixed now 🙏

**Comment by snicoll** [comment]
All good now, thanks for the follow-up.

**Pull request closed without merging**
