### PR TITLE
Use local storage to remember user choices

### PR DESCRIPTION
**Pull request by 4121nnn**
Caching implemented to these fields:
Project, Language, Spring boot, Packaging and Java version.

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hey @4121nnn, i pushed a commit to this PR which polishes a bit. What do you think of the changes?

I also removed the storage of the selected Boot version. I don't think that this brings much value, as the versions change every month.

**Comment by oodamien** [comment]
Closing in favour of https://github.com/spring-io/start.spring.io/pull/1462

**Comment by mhalbritter** [comment]
Hey @4121nnn, thanks for the PR. I had @oodamien looked at the PR, who has more understanding of React than I do. The local storage setting should be done in the reducer / context. He opened https://github.com/spring-io/start.spring.io/pull/1462 for that. Thanks anyway!

**Comment by 4121nnn** [comment]
No problem @mhalbritter, actually it is my first pull request ever. I will keep improving my skills. But thanks anyway for letting me participate in this project , I really appreciate that

**Pull request closed without merging**
