### PR TITLE
Adding MariaDB R2DBC and JDBC driver

### PR DESCRIPTION
**Pull request by rusher**
Adding MariaDB driver (JDBC and R2DBC)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rusher Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/start.spring.io&pullRequestId=584)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/start.spring.io&pullRequestId=584) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rusher Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/start.spring.io&pullRequestId=584)!

**Comment by snicoll** [comment]
@rusher thank you for making your first contribution to Spring Boot. Note that `api.json` in the `dev` directory is a dev-only resource to mock things when working on the client. We've renamed that on `master` to make that more explicit.

Also, for the record, we don't usually add a new entry to the site via a PR as [we have a process](https://github.com/spring-io/start.spring.io/issues/new?labels=type%3A+entry-proposal&template=add-entry-proposal.md) that folks should follow before working on the code. We've discussed this and we feel this entry is a little bit different (not a starter and clearly a driver that we missed from the list of the ones we managed). Thanks again!

**Comment by rusher** [comment]
perfect !

About the process, an addition to [CONTRIBUTING](https://github.com/spring-io/start.spring.io/blob/master/CONTRIBUTING.adoc) would be nice then, It wasn't explicit.

**Comment by snicoll** [comment]
Fair enough, I've added [a section](https://github.com/spring-io/start.spring.io/blob/master/CONTRIBUTING.adoc#proposal-for-new-entries). We also had an overdue issue to fix the PR template that I just fixed as well.

**Pull request closed without merging**
