### PR TITLE
Upgrade to Spring Cloud GCP 4.4.0 and 3.5.2

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Comment by snicoll** [comment]
@mpeddada1 looking at the [release notes for `4.4.0`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v4.4.0), it looks like this version is compatible with Spring Boot 3.1 (given the upgrade to Spring Cloud). Shouldn't we allow 4.4.0 to be used with Spring Boot 3.1 then? Currently, it is disabled.

**Comment by snicoll** [comment]
I made a judgment call based on https://github.com/GoogleCloudPlatform/spring-cloud-gcp#compatibility-with-spring-project-versions and enabled Spring Cloud GCP 4.4.0 on Spring Boot 3.1. @elefeint if that looks wrong please let me know and we can adjust.

**Comment by elefeint** [comment]
@meltsufin? Sorry, I left the project, so I don't actually know what the right thing here is.

**Comment by meltsufin** [comment]
@snicoll We are still trying to figure out if we can support Spring Boot 3.0 and 3.1 in the same branch. The [PR to update to 3.1](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1874) is currently red.

**Pull request closed without merging**
