### PR TITLE
A Spring Boot 3.0-based app that depends on PostgreSQL and Spring Data R2DBC uses the wrong coordinates for its r2dbc-postgresql dependency

### LINKED ISSUE #881: A Boot 3.0-based app that depends on PostgreSQL and Spring Data R2DBC uses the wrong coordinates for its r2dbc-postgresql dependency
It has [moved into the `org.postgresql` group](https://github.com/r2dbc/r2dbc-bom/issues/44) in Borca-M2. `R2dbcBuildCustomizer` should be updated accordingly.

### PR DESCRIPTION
**Pull request by tisonkun**
Reflect https://github.com/r2dbc/r2dbc-bom/issues/44

This closes #881.

Signed-off-by: tison <wander4096@gmail.com>

### CODE REVIEW

**Comment by tisonkun** [comment]
@wilkinsona I made a direct change on the `customize` method. But possibly there should be conditions based on Spring Boot versions selected. I'm trying to see whether these is some.

**Comment by wilkinsona** [comment]
Thanks for the PR, @tisonkun.

> But possibly there should be conditions based on Spring Boot versions selected

There should be. The new `org.postgresql` group should only be used with Boot 3.0. With 2.x, `io.r2dbc` needs to be used as before.

**Comment by tisonkun** [comment]
@wilkinsona I hope this is the pattern the starter handles different boot versions https://github.com/spring-io/start.spring.io/pull/882/commits/1aead5727e664652e387cec5c50c59ee80bebc3c.

**Comment by tisonkun** [comment]
cc @wilkinsona @snicoll could you please give this PR a review?

**Pull request closed without merging**
