### PR TITLE
Upgrade to Spring Cloud Services 2.1.0.RELEASE

### PR DESCRIPTION
**Pull request by habuma**

### CODE REVIEW

**Comment by snicoll** [comment]
@habuma this is a new feature release. Should this be tied to Spring Boot 2.0 or should we bump support as of Spring Boot 2.1?

**Comment by habuma** [comment]
Good point. Let me consider that and get back to you.

**Comment by habuma** [comment]
@snicoll Before I submit an update wrong...would the following ranges make sense to you?

```        mappings:
          - versionRange: "[1.5.0.RELEASE,1.5.x.BUILD-SNAPSHOT]"
            version: 1.6.6.RELEASE
          - versionRange: "[2.0.0.RELEASE,2.0.x.BUILD-SNAPSHOT]"
            version: 2.0.3.RELEASE
          - versionRange: "[2.1.0.RELEASE,2.1.x.BUILD-SNAPSHOT]"
            version: 2.1.0.RELEASE```

**Comment by snicoll** [comment]
Thanks for the quick feedback. The last range can just be `2.1.0.RELEASE` unless you want to restrict the usage of Spring Cloud Services with Spring Boot 2.2

**Comment by habuma** [comment]
Okay, so I just pushed that change. Let me know if there's anything else you see that could be improved. Otherwise, I'll eagerly await the merge.

**Comment by snicoll** [comment]
Thanks a lot, this is now live.

**Comment by habuma** [comment]
Awesome, thanks!

**Pull request closed without merging**
