### PR TITLE
Add Support for PubSub+ and the cloud streams binder

### PR DESCRIPTION
**Pull request by Mrc0113**
PubSub+ is a partner maintained Spring Cloud Streams binder advertised on the Spring Cloud Streams project page. It causes confusion with users when it is in the Spring docs, but not available via the Spring Initializr.

As a Pivotal partner, Solace worked with Pivotal to create the binder & starters so hopefully everything is ready to go, but if you see something missing please let me know.  

Here is a link to the binder’s repo: [https://github.com/SolaceProducts/spring-cloud-stream-binder-solace](https://github.com/SolaceProducts/spring-cloud-stream-binder-solace)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Mrc0113 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/start.spring.io&pullRequestId=127)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/start.spring.io&pullRequestId=127) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Mrc0113 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/start.spring.io&pullRequestId=127)!

**Comment by snicoll** [comment]
@Mrc0113 thanks for the PR but we have a process to request the addition of new dependencies to initializr. I'll put this PR on hold, please [create an issue](https://github.com/spring-io/start.spring.io/issues/new?template=new-entry-proposal.md) and fill in the template with the requested information.

**Comment by Mrc0113** [comment]
Thanks @snicoll - I'll work on getting the information together to create an issue for the request. 
It might be a good idea to add a link to that process to the README as well.

**Comment by snicoll** [comment]
See https://github.com/spring-io/start.spring.io/issues/107

**Comment by snicoll** [comment]
As discussed on the call, I am going to close this now. This PR is outdated and I'd like us to continue the discussion on #139

**Pull request closed without merging**
