### PR TITLE
History dialog does not adapt to dark theme

### PR DESCRIPTION
**Pull request by sanajitjana**
issue #1521 created previously.
Thanks @mhalbritter

### CODE REVIEW

**Comment by mhalbritter** [comment]
Hey, thanks for the PR, but the items are not really dark:

image

In the light version, the background is the same as the main site's background, and the items have the same color as the footer. On hover they get slightly lighter.

That's what should be applied to the dark theme, too.

**Comment by sanajitjana** [comment]
Yes @mhalbritter 

I kept the items' background as light white, similar to the light theme version. When hovering over an item, the primary color green (like the dependency item color) is applied.

Now, as you mentioned, I will change the item color to a darker shade like the footer.
And the item hover color will be still the same - primary color green (like the dependency item color).

Do a thumbs up if it's sounds okay,
and give me some time to make these changes.

**Comment by mhalbritter** [comment]
> And the item hover color will be still the same - primary color green (like the dependency item color).

Please us the same effect as the light theme does. It applies a `lighten` effect to the color.

**Comment by sanajitjana** [comment]
Hi @mhalbritter 
Here's come one more question - 

Once I applied dark-background on item
It's looks merging with background

image

Do your prefer to add border?

image

What's better?

**Comment by sanajitjana** [comment]
> If you look at the light mode, the background of the modal is the same as the background of the site (white).

I got you.
I used same color, and now it's looks this

image

**Comment by mhalbritter** [comment]
Cool, thanks! That looks good.

**Comment by sanajitjana** [comment]
@mhalbritter 

Thanks for your guidance.
Please let me know if anything is required.

**Comment by mhalbritter** [comment]
Thanks a lot @sanajitjana !

**Comment by sanajitjana** [comment]
> Thanks a lot @sanajitjana !

Thanks to you!
See you in the next PR 😀

**Comment by mhalbritter** [comment]
:+1: I got an additional tip for you: Your main branch contains commits from another of your pull requests. That's why this PR showed changes from the other PR:

image

To fix that, you should reset your main branch to the upstream:

```
git remote add upstream https://github.com/spring-io/start.spring.io.git
git fetch upstream
git reset --hard upstream/main
```

And then, if you work a new PR, create a branch (from main) for it:

```
git switch main
git pull upstream main # get newest changes
git branch -c my-new-feature
```

This way you can create a branch for every PR and commits don't get mixed up.

**Comment by sanajitjana** [comment]
> This way you can create a branch for every PR and commits don't get mixed up.

Thanks, I will follow the same.

**Pull request closed without merging**
