### PR TITLE
Upgrade to Okta Spring Boot 1.5.1

### PR DESCRIPTION
**Pull request by arvindkrishnakumar-okta**
Unable to submit the CLA. 

The form has a required dropdown field but does not list any option. This prevents me from being able to Submit the CLA form:

image

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@arvindkrishnakumar-okta Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/start.spring.io&pullRequestId=580)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/start.spring.io&pullRequestId=580) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by snicoll** [comment]
Thanks for the PR @arvindkrishnakumar-okta. I've never heard of that issue before, paging @rwinch for insights

**Comment by rwinch** [comment]
See if this helps https://cla.pivotal.io/about#corporate-signature-github-org

**Comment by snicoll** [comment]
@arvindkrishnakumar-okta can you please give it another look? Alternatively I can take care of the upgrade myself.

**Comment by arvindkrishnakumar-okta** [comment]
@rwinch @snicoll I'm seeing the same issue with the link that you provided above.

**Comment by arvindkrishnakumar-okta** [comment]
@snicoll any updates/feedback on this?

**Comment by snicoll** [comment]
I've already offered to upgrade on your behalf. I don't know what issue you're facing with the CLA tool I am afraid.

**Comment by mraible** [comment]
@snicoll I'll take you up on that offer! 😄

**Comment by snicoll** [comment]
This has been superseded by #589.

@arvindkrishnakumar-okta please follow-up on https://github.com/pivotalsoftware/pivotal-cla for that CLA signing problem.

**Comment by rwinch** [comment]
@arvindkrishnakumar-okta Are you suppose to be included in a corporate CLA from Okta? If so, from the link I provided:

If your company associated the signature to a GitHub organization, then you must ensure the following is true.

* Your GitHub account is a member of the selected organization
* You have made your [membership public](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)

At minimum your membership is not public because I cannot see it listed under your profile. You should be able to see the organization under your profile even if you are not logged in (you can use incognito window to check).

**Comment by arvindkrishnakumar-okta** [comment]
> @arvindkrishnakumar-okta Are you suppose to be included in a corporate CLA from Okta? If so, from the link I provided:
> 
> If your company associated the signature to a GitHub organization, then you must ensure the following is true.
> 
>     * Your GitHub account is a member of the selected organization
> 
>     * You have made your [membership public](https://help.github.com/articles/publicizing-or-hiding-organization-membership/)
> 
> 
> At minimum your membership is not public because I cannot see it listed under your profile. You should be able to see the organization under your profile even if you are not logged in (you can use incognito window to check).

@rwinch Thanks! I've just made my membership public.

**Pull request closed without merging**
